### ISSUE TITLE
[FEATURE] Test that headers can compile in isolation.

### ISSUE THREAD

**Issue by vector-of-bool** [vector-of-bool/dds#5]
**Describe the scenario and circumstances that should be addressed**

It is common for header files to accidentally become order-dependent, or to rely on other headers that may not be available to header consumers. This can cause compilation errors for consumers that `#include` headers in the incorrect order.

**Describe the solution you'd like**

`dds` should, in parallel with regular compilation, run a "syntax-only" pass over the headers of a project. For headers in `include/`, the `src/` directory should be intentionally omitted from the search-path as to prevent the public headers from relying on implementation headers.

**Comment by Quincunx271** [comment]
I did some investigation into implementing this and ran into an issue with gcc: gcc warns on `#pragma once` in "main file", and AFAICT, the warning can't be turned off ( https://godbolt.org/z/TKMfMoP7h ) (well, `-w` does it, but it also turns off all warnings).

Clang has a way to turn off the warning, and MSVC doesn't warn.

I suppose this means that the general way of implementing this would be to generate a .cpp file with just a `#include "the-header-file"` and compile that with `-fsyntax-only`.

**Comment by Quincunx271** [comment]
I suppose we could pipe in the `#include "the-header-file"` to gcc and avoid the need to generate an actual file.

**Comment by vector-of-bool** [comment]
Added in #78
