### ISSUE TITLE
[BUG] dds-ci doesn't build at HEAD

### ISSUE THREAD

**Issue by Quincunx271** [vector-of-bool/dds#113]
**Describe the bug**

I synced to HEAD (d616fcec4e82a19b9d21cd7bd6c68d0d625cbf9a) and attempted to build (`dds-ci`; I also tried with `--clean`), but it doesn't build, with a syntax check on dds.test.hpp stating "fatal error: catch2/catch.hpp: No such file or directory".

**Steps to Reproduce**

```bash
$ git switch develop
$ git checkout d616fcec4e82a19b9d21cd7bd6c68d0d625cbf9a
$ poetry shell
$ dds-ci
```

**`dds-ci` Output**

```
[error] Syntax check failed: /home/path/to/dds/src/dds/dds.test.hpp
[error] Subcommand FAILED [Exited 1]: /usr/bin/ccache g++-10 -fdiagnostics-color -D __dds_cachebust=1728444582 -fsyntax-only -xc++ -I src -isystem /home/path/to/dds/_prebuilt/ci-repo/boost.leaf@1.78.0/include -isystem /home/path/to/dds/_prebuilt/ci-repo/ctre@2.8.1/include -isystem /home/path/to/dds/_prebuilt/ci-repo/fmt@6.2.1/include -isystem /home/path/to/dds/_prebuilt/ci-repo/magic_enum@0.7.3/include -isystem /home/path/to/dds/_prebuilt/ci-repo/ms-wil@2020.3.16/include -isystem /home/path/to/dds/_prebuilt/ci-repo/neo-buffer@0.5.2/src -isystem /home/path/to/dds/_prebuilt/ci-repo/neo-compress@0.3.1/src -isystem /home/path/to/dds/_prebuilt/ci-repo/neo-fun@0.11.1/src -isystem /home/path/to/dds/_prebuilt/ci-repo/neo-http@0.2.0/src -isystem /home/path/to/dds/_prebuilt/ci-repo/neo-io@0.2.3/src -isystem /home/path/to/dds/_prebuilt/ci-repo/neo-sqlite3@0.7.1/src -isystem /home/path/to/dds/_prebuilt/ci-repo/neo-url@0.2.5/src -isystem /home/path/to/dds/_prebuilt/ci-repo/nlohmann-json@3.9.1/include -isystem /home/path/to/dds/_prebuilt/ci-repo/pubgrub@0.3.1/src -isystem /home/path/to/dds/_prebuilt/ci-repo/range-v3@0.11.0/include -isystem /home/path/to/dds/_prebuilt/ci-repo/semver@0.2.2/src -isystem /home/path/to/dds/_prebuilt/ci-repo/spdlog@1.7.0/include -isystem /home/path/to/dds/_prebuilt/ci-repo/sqlite3@3.35.2/src -isystem /home/path/to/dds/_prebuilt/ci-repo/vob-json5@0.1.6/src -isystem /home/path/to/dds/_prebuilt/ci-repo/vob-semester@0.3.1/src -isystem /home/path/to/dds/_prebuilt/ci-repo/yaml-cpp@0.7.0/include -isystem /home/path/to/dds/_prebuilt/ci-repo/zlib@1.2.9/include -I conf -Wall -Wextra -Wpedantic -Wconversion -Werror -MD -MF /home/path/to/dds/_build/timestamps/dds/dds.test.hpp.o.d -MQ /home/path/to/dds/_build/timestamps/dds/dds.test.hpp.o -c /home/path/to/dds/_build/timestamps/dds/dds.test.hpp.syncheck -o/home/path/to/dds/_build/timestamps/dds/dds.test.hpp.o -g -fconcepts-diagnostics-depth=10 -fcoroutines -std=c++20 -fPIC -pthread
In file included from /home/path/to/dds/_build/timestamps/dds/dds.test.hpp.syncheck:1:
/home/path/to/dds/src/dds/dds.test.hpp:4:10: fatal error: catch2/catch.hpp: No such file or directory
    4 | #include <catch2/catch.hpp>
	      |          ^~~~~~~~~~~~~~~~~~
		  compilation terminated.
```

**Desktop (please complete the following information):**

 - Operating System: Ubuntu 20.04
 - Compiler: GCC 10
 - `dds` Version: d616fcec4e82a19b9d21cd7bd6c68d0d625cbf9a

**Comment by vector-of-bool** [comment]
Sorry for the upset. The CI process has changed up recently after I merged a massive pile of commits that I've been sitting on for a while (bad practice, eh...)

`dds` is now built using the Dagon tool. Run `poetry install` again and `dagon -lt` in the Poetry shell to see the build targets. I need to clean up and update the dev docs to reflect this. Tell me if you hit any immediate roadblocks that I'll need to address.

**Comment by vector-of-bool** [comment]
The above comment is incorrect. Something's wonky on `develop`. I thought I had fully merged `feature/dagon-ci`, but it still has some outstanding changes. Stay tuned.

**Comment by vector-of-bool** [comment]
Everything seems stable again now. Re-pasting comment now that it is accurate:

---

`dds` is now built using the Dagon tool. Run poetry install again and `dagon -lt` in the Poetry shell to see the build targets. I need to clean up and update the dev docs to reflect this. Tell me if you hit any immediate roadblocks that I'll need to address.
